// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xlbbbxucqvmxbzfrjgyi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhsYmJieHVjcXZteGJ6ZnJqZ3lpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcwMDgxOTQsImV4cCI6MjA2MjU4NDE5NH0.PGDbZqJqfiw8xBeY64Dci7AIpyI70MSOYKW8p9QwF5c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);